#!/bin/bash
source ~/myUtils/BASH_LIB_UTILS.sh
td_bin='~/myUtils/td'
wait_for=0.1

function tmux_work()
{

    zeus ${1}

    tmux new-window  -t "${1}:1" -n "DC1"
    tmux send-keys 'source ~/.bashrc' 'C-m' 'C-l'
    tmux selectp -t "${1}:1"
    tmux split-window -v
    tmux send-keys 'source ~/.bashrc' 'C-m' 'C-l'

    tmux new-window  -t "${1}:2" -n "Branch1"
    tmux send-keys 'source ~/.bashrc' 'C-m' 'C-l'
    tmux selectp -t "${1}:2"
    tmux split-window -v
    tmux send-keys 'source ~/.bashrc' 'C-m' 'C-l'

    tmux new-window  -t "${1}:3" -n "RTRs"
    tmux send-keys 'source ~/.bashrc' 'C-m' 'C-l'
    tmux selectp -t "${1}:3"
    tmux split-window -v
    tmux send-keys 'source ~/.bashrc' 'C-m' 'C-l'

    tmux new-window  -t "${1}:4" -n "Work"
    tmux send-keys 'source ~/.bashrc; cd ~/ws/; penv' 'C-m' 'C-l'

    tmux new-window  -t "${1}:5" -n "Work"
    tmux send-keys 'source ~/.bashrc; cd ~/ws/; penv' 'C-m' 'C-l'

    tmux new-window  -t "${1}:6" -n "Lib"
    tmux send-keys 'source ~/.bashrc; cd ~/ws/; penv' 'C-m' 'C-l'

    tmux new-window  -t "${1}:7" -n "Lib"
    tmux send-keys 'source ~/.bashrc; cd ~/ws/; penv' 'C-m' 'C-l'

    tmux new-window  -t "${1}:8" -n "Logs"
    tmux send-keys 'source ~/.bashrc; cd ~/logs/brizo; penv' 'C-m' 'C-l'

    tmux new-window  -t "${1}:9" -n "Notes"
    tmux send-keys 'source ~/.bashrc; cd ~/notes; penv' 'C-m' 'C-l'
    tmux selectp -t "${1}:9"
    tmux split-window -h
    tmux send-keys 'source ~/.bashrc; htop' 'C-m' 'C-l'
    tmux split-window -v
    tmux send-keys 'source ~/.bashrc' 'C-m' 'C-l'

}

function link_work()
{
    # getting windows from Work session
    tmux link-window -s Work:4 -t ${1}:4
    tmux link-window -s Work:5 -t ${1}:5
    tmux link-window -s Work:6 -t ${1}:6


    # getting windows from Work session
    tmux link-window -s Work:8 -t ${1}:8
    tmux link-window -s Work:9 -t ${1}:9
}

function create_work_windows()
{
    git_path="${HOME}/ws/${1}"
    mkdir -p "${git_path}"

    tmux new-window  -t "${1}:4" -n "Work"
    tmux send-keys "source ~/.bashrc; cd ${git_path}; penv" 'C-m' 'C-l'

    tmux new-window  -t "${1}:5" -n "Lib"
    tmux send-keys "source ~/.bashrc; cd ${git_path}; penv" 'C-m' 'C-l'

    tmux new-window  -t "${1}:6" -n "Lib"
    tmux send-keys "source ~/.bashrc; cd ${git_path}; penv" 'C-m' 'C-l'

    tmux link-window -s Work:9 -t ${1}:9
}

function CGNX_Local_Sessions()
{
    tmux new-window  -t "${1}:1" -n "Elem1"
    tmux send-keys "source ~/.bashrc; sshpass -p pass ssh admin1@10.9.120.113" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:1"
    tmux split-window -h
    tmux send-keys "source ~/.bashrc; sshpass -p pass ssh admin1@10.9.120.114" 'C-m'
    sleep $wait_for
    tmux split-window -h
    tmux send-keys "source ~/.bashrc; sshpass -p pass ssh admin1@10.9.120.123" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:2" -n "WAN_VYOS"
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.111" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:2"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.112" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.103" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.104" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:3" -n "LAN_VYOS"
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.121" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:3"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.122" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:7" -n "CTLR"
    tmux send-keys "source ~/.bashrc; sshpass -p ubuntu ssh ubuntu@10.9.120.5" 'C-m'
    tmux select-layout tile

    tmux new-window  -t "${1}:8" -n "Logs"
    tmux send-keys 'source ~/.bashrc; cd ~/logs/local; penv' 'C-m' 'C-l'
    tmux select-layout tile
}

function CGNX_Tprod_Sessions()
{
    tmux new-window  -t "${1}:1" -n "Elem1"
    tmux send-keys "source ~/.bashrc; sshpass -p pass ssh admin1@10.9.120.13" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:1"
    tmux split-window -h
    tmux send-keys "source ~/.bashrc; sshpass -p pass ssh admin1@10.9.120.14" 'C-m'
    sleep $wait_for
    tmux split-window -h
    tmux send-keys "source ~/.bashrc; sshpass -p pass ssh admin1@10.9.120.23" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:2" -n "WAN_VYOS"
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.11" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:2"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.12" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.3" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.4" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:3" -n "LAN_VYOS"
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.21" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:3"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; sshpass -p vyos ssh vyos@10.9.120.22" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:7" -n "CTLR"
    # tmux send-keys "source ~/.bashrc; sshpass -p ubuntu ssh ubuntu@10.9.120.5" 'C-m'
    tmux select-layout tile

    tmux new-window  -t "${1}:8" -n "Logs"
    tmux send-keys 'source ~/.bashrc; cd ~/logs/tprod; penv' 'C-m' 'C-l'
    tmux select-layout tile
}

function CGNX_Sessions()
{
    tmux new-window  -t "${1}:1" -n "Branch"
    tmux send-keys "source ~/.bashrc; $td_bin -d BR-SITE1-ELEM1" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:1"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -d BR-SITE2-ELEM1" 'C-m'
    sleep $wait_for
    tmux split-window -h
    tmux send-keys "source ~/.bashrc; $td_bin -d BR-SITE2-ELEM2" 'C-m'
    sleep $wait_for
    # tmux select-layout tile

    tmux new-window  -t "${1}:2" -n "DC"
    tmux send-keys "source ~/.bashrc; $td_bin -d DC-SITE1-ELEM1" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:2"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -d DC-SITE2-ELEM1" 'C-m'
    sleep $wait_for
    tmux split-window -h
    tmux send-keys "source ~/.bashrc; $td_bin -d DC-SITE2-ELEM2" 'C-m'
    sleep $wait_for
    # tmux select-layout tile

    tmux new-window  -t "${1}:3" -n "VYOS"
    tmux send-keys "source ~/.bashrc" 'C-m'

    tmux new-window  -t "${1}:7" -n "CTLR"
    tmux send-keys "source ~/.bashrc; sshpass -p \"Cgenix!@#\" ssh autotester@${1}" 'C-m'
    tmux select-layout tile

    log_path="${HOME}/logs/${1}"
    mkdir -p ${log_path}
    tmux new-window  -t "${1}:8" -n "Logs"
    tmux send-keys "source ~/.bashrc; cd ${log_path}; penv" 'C-m' 'C-l'
}



function NSG_Sessions()
{
    tmux new-window  -t "${1}:1" -n "VSC-Console"
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-g --console" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:1"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-h --console" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-i --console" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-j --console" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:2" -n "VSC-session"
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-g" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:2"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-h" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-i" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d dut-j" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:3" -n "NSG(OVS)"
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1}  -d ovs-1" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:3"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1}  -d ovs-2" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1}  -d ovs-3" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1}  -d ovs-4" 'C-m'
    sleep $wait_for
    tmux select-layout tile

    tmux new-window  -t "${1}:7" -n "SR/VSD"
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d esr.b --console" 'C-m'
    sleep $wait_for
    tmux selectp -t "${1}:7"
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d esr.c --console" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1} -d esr.f --console" 'C-m'
    sleep $wait_for
    tmux split-window -v
    tmux send-keys "source ~/.bashrc; $td_bin -t ${1}  -d vsd-1" 'C-m'
    sleep $wait_for
    tmux select-layout tile
}

function harness()
{
    tmux new-session -d -s "${1}" -n "harness" 
    tmux selectp -t "${1}:0"
    tmux split-window -h
    tmux send-keys 'C-m' "source ~/.bashrc; $td_bin -t ${1} --exec \"source /opt/rh/python27/enable;source /tmp/harness/bin/activate;cd /home/stupakul/ws/harness/nuage-tests//\"" 'C-m'
    sleep $wait_for
}

function zeus()
{
    tmux new-session -d -s "${1}" -n "zeus" 
    tmux setenv _TB_ ${1}
    tmux setenv TB ${1}
    tmux selectp -t "${1}:0"
    tmux split-window -h
    tmux send-keys 'C-m' "source ~/.bashrc; cd ~/ws/${1}/; penv" 'C-m'
    sleep $wait_for
}


function tmux_cgnx_lcl_ctlr()
{
    zeus ${1}
    CGNX_Local_Sessions ${1}
    link_work ${1}
}

function tmux_cgnx_tprod_ctlr()
{
    zeus ${1}
    CGNX_Tprod_Sessions ${1}
    link_work ${1}
}

function tmux_cgnx_ctlr()
{
    path="${HOME}/ws/${1}"
    mkdir -p "${path}"
    zeus ${1}
    CGNX_Sessions ${1}
    create_work_windows ${1}
}


function tmux_nsg()
{
    harness ${1}
    NSG_Sessions ${1}
    link_work ${1}
}

function tmux_checkgash()
{
    harness ${1}
    link_work ${1}
}

function tmux_monitor()
{
    return
}


function tmux_default()
{
    tmux new-session -s "${1}"   -n "Gash" -d
    tmux new-window  -t "${1}:1" -n "Work"
    tmux new-window  -t "${1}:2" -n "Work"
    tmux new-window  -t "${1}:3" -n "Work"
}

function tmux_sase()
{
    tmux new-session -s "${1}"   -n "Exec" -d
    tmux selectp -t "${1}:0"
    tmux split-window -h
    tmux send-keys "source ~/.bashrc; penv; export PYTHONPATH=~/cherry" 'C-m'
    tmux new-window  -t "${1}:4" -n "Work"
    tmux send-keys "source ~/.bashrc; penv; export PYTHONPATH=~/cherry" 'C-m'
    tmux new-window  -t "${1}:5" -n "Work"
    tmux send-keys "source ~/.bashrc; penv; export PYTHONPATH=~/cherry" 'C-m'
    tmux new-window  -t "${1}:6" -n "Work"
    tmux send-keys "source ~/.bashrc; penv; export PYTHONPATH=~/cherry" 'C-m'
    tmux new-window  -t "${1}:7" -n "Controller"
    tmux send-keys "source ~/.bashrc; penv; export PYTHONPATH=~/cherry" 'C-m'
    # getting windows from Work session
    tmux link-window -s Work:8 -t ${1}:8
    tmux link-window -s Work:9 -t ${1}:9

}


function my_help()
{

    echo "Usage: $(basename $0) <session_name> [<testbed_type=nsg>]"
    exit 0
}


if [ $# -eq 0 ]; then 
    tmux attach
else
    if [ $1 == "--help" -o $1 == "-h" ]; then
        my_help
    #else
    #    tmux attach -t ${1} || tmux new -s ${1}
    #fi
    #exit 0
    # old code (deprecated)
    elif [ $(tmux ls | grep -c -- "${1}:") -gt 0 ]; then
        boxify "Attaching TMUX session $1"
        opinion="y"
    else
        log_msg -n "No existing session with name \"$1\". Do you want me to start a new session [y] : "
        read opinion
        if [ -z ${opinion} ]; then
            opinion="y"
        fi
        if [ ${opinion} == "y" ]; then
            # start tmux-server is not running
            log_msg -n "Creating and customizing tmux session ... "
            tmux start-server
            if [ $# -eq 2 ]; then
                case $(echo $2 | tr '[:upper:]' '[:lower:]') in
                    "local")
                        tmux_cgnx_lcl_ctlr $1;;
                    "tprod")
                        tmux_cgnx_tprod_ctlr $1;;
                    "nsg")
                        tmux_cgnx_ctlr $1;;
                    "sase")
                        tmux_sase $1;;
                    *)
                        echo "$2: mapping yet to specify"
                        exit -1;;
                esac
            else
                case $(echo $1 | tr '[:upper:]' '[:lower:]') in
                    "work*")
                        tmux_work $1;;
                    *gash*)
                        tmux_checkgash $1;;
                    "default")
                        tmux_default $1;;
                    "local")
                        tmux_cgnx_lcl_ctlr $1;;
                    "tprod")
                        tmux_cgnx_tprod_ctlr $1;;
                    "sase")
                        tmux_sase $1;;
                    *)
                        tmux_cgnx_ctlr $1;;
                esac
            fi
            log_msg "[Done]"
       fi
    fi
    if [ ${opinion} == "y" ]; then
        log_msg -n "Attaching session ... "
        sleep 0.5
        tmux attach-session -d -t ${1}
    fi
fi
set +x
